create sequence history_sequence start with 1 increment by 1;
create sequence menu_item_sequence start with 1 increment by 1;
create sequence order_sequence start with 1 increment by 1;
create sequence post_sequence start with 1 increment by 1;
create sequence profile_sequence start with 1 increment by 1;
create sequence restaurant_sequence start with 1 increment by 1;
create sequence user_sequence start with 1 increment by 50;
create table history (id bigint not null, order varchar(255) not null, performed_at date not null, order_id bigint, user_id bigint not null, primary key (id));
create table menu_item (id bigint not null, category varchar(255) not null, image mediumblob, ingredients varchar(255) not null, name varchar(255) not null, subcategory varchar(255), thickness varchar(255), order_id bigint, primary key (id));
create table menu_item_sizes_and_prices (menu_item_id bigint not null, sizes_and_prices double, sizes_and_prices_key integer not null, primary key (menu_item_id, sizes_and_prices_key));
create table order (id bigint not null, created_at timestamp not null, number_of_cutlery integer not null, status varchar(255) not null, total_cost double not null, user_id bigint, primary key (id));
create table post (id bigint not null, image mediumblob, summary varchar(1000), text varchar(10000) not null, title varchar(500) not null, user-id bigint, primary key (id));
create table profile (id bigint not null, address varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
create table restaurant (id bigint not null, address varchar(255) not null, contact_number varchar(255), coordinates varchar(255) not null, work_hours_in_weekend varchar(255) not null, work_hours_in_work_days varchar(255) not null, primary key (id));
create table service (id bigint not null, contact_number varchar(255), description varchar(255), image varbinary(255), title varchar(255), primary key (id));
create table user (id bigint not null, created_at timestamp, email varchar(255) not null, last_updated timestamp, nickname varchar(255) not null, password varchar(255) not null, profile_id bigint, primary key (id));
alter table user add constraint user_email_unique unique (email);
alter table user add constraint user_nickname_unique unique (nickname);
alter table history add constraint FKeoutpmcqvjtikot0tltndrdr4 foreign key (order_id) references order;
alter table history add constraint FKn4gjyu69m6xa5f3bot571imbe foreign key (user_id) references user;
alter table menu_item add constraint FKkw4vsrb1d8kmydh9cx47n48w1 foreign key (order_id) references order;
alter table menu_item_sizes_and_prices add constraint FKhsnajus706mr2rhmrrek08vh3 foreign key (menu_item_id) references menu_item;
alter table order add constraint FKt7abetueht6dd1gs9jyl3o4t7 foreign key (user_id) references user;
alter table post add constraint FKfbk3qvf30b2x8vruoh2x32hhi foreign key (user-id) references user;
alter table user add constraint FKof44u64o1d7scaukghm9veo23 foreign key (profile_id) references profile;
